name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: make gradelw executable
      run: chmod +x gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and tag Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/java-maven:latest .
  

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/java-maven:latest


