name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: make gradelw executable
      run: chmod +x gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew build


